# APPLICATION NAME
spring:
  application:
    name: article-service
# DATASOURCE
  datasource:
    url: jdbc:postgresql://localhost:5432/article_db
    username: postgres
    password: postgres
# HIBERNATE-JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# LIQUIBASE
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
# SERVER PORT
server:
  port: 8081