# APPLICATION NAME
spring:
  application:
    name: article-service
# MONGODB
  data:
    mongodb:
      uri: mongodb://localhost:27017/article_db
# SERVER PORT
server:
  port: 8081
# OPEN API
open-api-properties:
  info:
    contact:
      name: Oscar
      email: oscarherenciasakkis@gmail.com
      url: oscarherenciasakkis.com
    description: Article Service
    title: Article Service
    version: 0.0.1
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
    termsOfService: http://swagger.io/terms/
  server:
    description: Local server
    url: http://localhost:8081